### PR TITLE
(Maint) Ensure canonicalize correctly compares sorted hashes

### PR DESCRIPTION
**Pull request by Hvid**
Implements different sorting of Hash and Array values.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @Hvid I would like to thank you for taking the time to create this PR. 

In our testing currently there are test failures, and at this particular time they are rubocop failures, it would be great if you could work on getting these resolved so we are 1 step closer to getting this PR merged.

**Comment by Hvid** [comment]
Hi @pmcmaw 

Thanks, ruby is not really my home turf, but i gave it a go :)

**Comment by pmcmaw** [comment]
No worries @Hvid, for it not being your home turf you've done a pretty decent job. Im going to add Michael for a review as he is the specialist in this particular area. But honestly, nice work for picking it up and just going with it :-) Thank you!

**Review by michaeltlombardi — APPROVED** [review]
Awesome, thanks so much for the contribution @Hvid! 🎉 LGTM!

**Pull request merged**
